### ISSUE TITLE
MIlestone 2 feedback 

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/dsci-532_group-20#44] opened 2021-01-30 08:01 UTC
Hi Team 20,

- The overall layout is nice and clean. Not too cluttered and well spaced. There is a small grammatical error in the statement below your title
- the selections in the drop-down menu are nice. I’m almost wishing to be able to see some of these graphs combined. Like number of adults, children, babies. I would like to be able to see all these lines in one plot or in multiple plots so I can more easily compare and make judgements with this information. I can see that there are definitely very different time trends for all three demographic groups.
- since the y-axis values in the main plot change with each variable it makes comparison very difficult to calculate just by looking at the graph.
- I don’t think the slider is accurately aligned with the scale/words/graph axis. at least it is a little confusing because if I put both dots on the winter dot I get only wk 48 so I am not sure how to select all weeks considered part of the winter etc. The slider scale also goes beyond the 4 selections, and if the extra range isn’t kept then you don’t see all the information. I think some of the early chronological weeks would be part of winter and this is not clear it is aligned this way right now. I’m sure this is a bug you are aware of, and are improving!
- I really like what you have done with the bar plots on the bottom. These are currently the strongest and most useful plots in the current deployment version. They are easy to understand and think about what I would do with this data if I were designing a marketing campaign.

**Comment by chenzhao299** [comment] 2021-02-07 03:06
Hello Analise, 

Thank you very much for your feedback. They are very helpful. We tried our best to address all the issues, here listed what we did:

- We changed the grammar for the subtitle and added more details about the app
- We found out for all the features, there is less information provided by just comparing them to each other. In the app proposal, we were trying to add a correlation plot to compare them initially, but removed it after discussion
- We added another new plot besides the original one to make it easier for comparison. Now the one on the left is on month scale and the one on the right is on day scale. Users can select which feature they want to know about, and compare it between the average of whole time and the month they defined
- We removed the slider and used the new plots to provide information with more details. Now the users can select which year and month they want to see and do scrolling on the plots to show more information. And because we added callback connecting both dropdown menus on the left, the dashboard doesn't have any error caused by missing data by our testing
- Thank you for your comments on the bottom bar plots. We changed the left bar plot to only include the top 10 countries other than top 20, since the countries from 10 to 20 doesn't have many guests and it will make the output clearer

As far as we concerned, we solved all the issued in the feedback. Thank you very much for your advice and suggestions! We are closing this issue now.

**Closed as completed by chenzhao299** 2021-02-07 03:06 UTC
